name: Generate Signing Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore AI-Study-Uddy-release.keystore \
            -alias aistudyuddy \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "AIStudyUddy@2026" \
            -keypass "AIStudyUddy@2026" \
            -dname "CN=AI Study Uddy, OU=App, O=AI Study Uddy, L=Shimla, ST=Himachal Pradesh, C=IN"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: AI-Study-Uddy-Release-Keystore
          path: AI-Study-Uddy-release.keystore
